// src/blessed/commandments.ts
import type { EXAMPLES } from "./examples";

export interface Commandment {
  n: number; tag: string; title: string;
  verdict: "Obvious" | "Sensible" | "Correct" | "Overdue" | "Necessary";
  body: string; snippet: string; example?: keyof typeof EXAMPLES;
}

export const COMMANDMENTS: Commandment[] = [
  { n: 1, tag: "THE INDEX PRINCIPLE", title: "Arrays are zero-indexed, and the index is the offset from the start", verdict: "Obvious",
    body: "An index is an offset: how far from the beginning? The beginning is zero distance from itself. This is geometry. Slices are half-open, so length = end - start, and negative indices count from the end because that is the only sensible thing they could mean.",
    snippet: `let fruits = ["apple", "banana", "mango"]\nprint(fruits[0..2])\nprint(fruits[-1])`, example: "hello" },
  { n: 2, tag: "THE TYPE SANCTITY", title: "Types are inferred, explicit when ambiguous, and never coerced silently", verdict: "Sensible",
    body: "BLESSED infers types from assignment. You may annotate for clarity. What BLESSED will not do, under any circumstances, is silently convert one type to another and pretend nothing happened. If you add a String and an Int, BLESSED stops and asks what you meant. Out loud.",
    snippet: `let x = 5\nlet label: String = "five"\nprint(String(x) + " is " + label)`, example: "strictTypes" },
  { n: 3, tag: "THE EQUALITY COMMAND", title: "There is one equality operator, and it compares values", verdict: "Obvious",
    body: "== compares values, structurally, all the way down. Comparing an Int to a String is a compile error, not false. If you want to know whether two things are the same object, that is a different question, so it has a different operator: is.",
    snippet: `let a = [[1, 2], [3]]\nlet b = [[1, 2], [3]]\nprint(a == b)\nprint(a is b)`, example: "oneEquality" },
  { n: 4, tag: "THE STYLE BOUNDARY", title: "Four spaces, braces, and a formatter that is not a suggestion", verdict: "Overdue",
    body: "Indentation is four spaces. Blocks use braces, so copy-pasting code never silently changes its meaning. The formatter enforces all of it. Every argument about style has already been had, and it has been resolved.",
    snippet: `let total = 0\nloop n in [1, 2, 3] {\n    total = total + n\n}\nprint(total)` },
  { n: 5, tag: "THE NULL REDEMPTION", title: "Nullability is in the type, and the compiler makes you handle it", verdict: "Necessary",
    body: "String? can be null. String cannot. Using a nullable value without handling it is a compile error. Handle it with ??, with if let, or with match. There is exactly one kind of nothing.",
    snippet: `let nick: String? = null\nprint(nick ?? "no nickname")\nif let n = nick {\n    print(n)\n}`, example: "nullSafe" },
  { n: 6, tag: "THE NAMING CODE", title: "camelCase for variables, SCREAMING_SNAKE for constants, and nothing else", verdict: "Sensible",
    body: "A snake_case variable is reformatted to camelCase with a note. An ALL_CAPS name is a constant and cannot be reassigned. Leading underscores belong to the compiler. Double underscores on both sides are not a thing. This is BLESSED, not Python.",
    snippet: `let MAX_RETRIES = 3\nlet retryCount = 0\nprint(MAX_RETRIES - retryCount)` },
  { n: 7, tag: "THE SEMICOLON PEACE", title: "Semicolons are optional, and the formatter removes them", verdict: "Obvious",
    body: "A line ends a statement. Type a semicolon if your fingers insist. The formatter will vaporize it and let you know. Suffer no more.",
    snippet: `let x = 1\nprint(x)` },
  { n: 8, tag: "THE INTERPOLATION HARMONY", title: "Strings interpolate with ${}, and that is the only way to build them", verdict: "Sensible",
    body: "No format strings, no concatenation ladders, no printf. Put the expression in the string. The expression can be anything, including another string.",
    snippet: `let who = "World"\nprint("Hello, \${who.upper()}! You have \${[1, 2, 3].length} messages.")` },
  { n: 9, tag: "THE BOOLEAN PURITY", title: "Conditions are Bool, and only Bool", verdict: "Correct",
    body: "Bool is a type. true and false are its values. An Int is not a Bool, an empty String is not a Bool, and null is not a Bool. BLESSED is not interested in truthy and falsy load-bearing conventions that were always wrong. Say what you mean.",
    snippet: `let name = ""\nif name != "" {\n    print("named")\n} else {\n    print("anonymous")\n}` },
  { n: 10, tag: "THE SINGLE LOOP", title: "There is one loop keyword, and its shape adapts to what you give it", verdict: "Obvious",
    body: "loop { } runs forever. loop cond { } repeats while true. loop x in xs { } iterates. Add despite errors to keep going when an iteration fails, and as e to get a String? holding the most recent complaint, null until there is one. One concept, one keyword.",
    snippet: `loop d in [2, 0, 5] despite errors as e {\n    print(10 / d)\n}\nprint(e ?? "no complaints")`, example: "loopModifier" },
  { n: 11, tag: "THE BRANCH", title: "if, else if, else, and nothing cleverer", verdict: "Obvious",
    body: "Branches read top to bottom. The condition is a Bool. There is no ternary, no switch on fallthrough, no goto wearing a hat.",
    snippet: `let n = 7\nif n < 5 {\n    print("small")\n} else if n < 10 {\n    print("medium")\n} else {\n    print("large")\n}` },
  { n: 12, tag: "THE FUNCTION", title: "fn declares a function, functions are values, and a single expression needs no return", verdict: "Sensible",
    body: "Parameters are typed. The return type is inferred unless you say otherwise. Anonymous functions use the same keyword, because it is the same thing. No overloading, no default arguments, no magic. Recursion is allowed up to 500 frames, which is deeper than your call stack of excuses.",
    snippet: `fn twice(f: Fn(Int) -> Int, x: Int) -> Int { f(f(x)) }\nprint(twice(fn(n: Int) { n * 3 }, 2))`, example: "functions" },
  { n: 13, tag: "THE RECORD", title: "Records are immutable, constructed with named fields, and compared by value", verdict: "Correct",
    body: "Positional arguments were always a guessing game. Name every field, every time. Records do not change; make a copy with `with`. Two records with the same fields are equal, because of course they are.",
    snippet: `record Point { x: Int, y: Int }\nlet p = Point(x: 1, y: 2)\nlet q = p with { y: 5 }\nprint(q)\nprint(p == Point(x: 1, y: 2))`, example: "records" },
  { n: 14, tag: "THE MAP", title: "Maps are typed, keyed by String or Int, and a missing key is null", verdict: "Sensible",
    body: "A lookup might miss. The type says so: looking up an Int value gives you Int?, and the null rules apply. No exceptions, no default-value arguments, no silence.",
    snippet: `let ages = {"al": 30}\nprint(ages["al"] ?? 0)\nprint(ages["bo"] ?? 0)\nprint(ages.has("al"))`, example: "records" },
  { n: 15, tag: "THE MATCH", title: "match destructures, guards, and refuses to leave a case uncovered", verdict: "Necessary",
    body: "Arms are literals, bindings, bindings with guards, record patterns, or the wildcard. A match without a wildcard or a binding is a compile error. Match is an expression. BLESSED does not do surprise endings.",
    snippet: `let label = match 7 {\n    0 -> "zero"\n    n if n > 5 -> "big"\n    _ -> "small"\n}\nprint(label)`, example: "matching" },
  { n: 16, tag: "THE ERROR", title: "fail raises a message, and only despite errors catches it", verdict: "Correct",
    body: "There are no try blocks, no exception hierarchies, no checked and unchecked. Something goes wrong, you say so in words. The loop that can tolerate it says despite errors. Everything else stops, which is what you wanted.",
    snippet: `loop x in [1, 2, 3] despite errors as e {\n    if x == 2 {\n        fail "two is not welcome"\n    }\n    print(x)\n}`, example: "errors" },
  { n: 17, tag: "INFINITY, AND THE NUMBER THAT IS NOT", title: "Float has Infinity. It does not have NaN.", verdict: "Correct",
    body: "1.0 / 0.0 is Infinity, which is a perfectly good number for limits and sentinels. 0.0 / 0.0 is not a number, and BLESSED will not pretend it is: it fails. Int has no infinity, because Int is a count and there is no infinite count.",
    snippet: `print(1.0 / 0.0)\nprint(Infinity > 1000000.0)\nprint(-Infinity < 0.0)`, example: "math" },
  { n: 18, tag: "IMAGINARY NUMBERS ARE REAL", title: "Complex is a type, written the way mathematicians write it", verdict: "Overdue",
    body: "3 + 4i is a Complex. Complex only mixes with Complex, so convert on purpose. Complex numbers have no order; neither does your argument. The square root of -4.0 is a runtime error on Float and 2i on Complex.",
    snippet: `let z = 3 + 4i\nprint(z.abs())\nprint(z * z.conj())\nprint(Complex(-4.0).sqrt())`, example: "math" },
  { n: 19, tag: "RANGES ARE VALUES", title: "a..b is a List<Int>, half-open, and it goes wherever a list goes", verdict: "Obvious",
    body: "0..3 is [0, 1, 2]. Use it in a loop, map over it, slice with it. A range large enough to exhaust memory fails before it tries.",
    snippet: `print(0..5)\nprint((1..4).map(fn(n) { n * n }))\nprint(["a", "b", "c", "d"][1..3])` },
  { n: 20, tag: "OVERFLOW IS NOT OUR PROBLEM", title: "Int is arbitrary precision", verdict: "Necessary",
    body: "There is no MAX_INT, no wraparound, no silent precision loss past 2^53. 25.factorial() is exact. Overflow was a hardware limitation. BLESSED declined to inherit it.",
    snippet: `print(2.pow(100))\nprint(25.factorial())\nprint(9007199254740993 + 1)`, example: "strictTypes" },
  { n: 21, tag: "THE ORDER OF THINGS", title: "A variable exists after the line that creates it. Not before. This is time.", verdict: "Obvious",
    body: "Functions are hoisted, so you may call one before the line you wrote it on. Variables are not. A function that reads a variable needs that variable declared above the earliest line the function could run. The compiler will not trace every call path to prove you got away with it. You know when the variable exists. You typed it. Put the let above the function. BLESSED considered the clever alternative for four minutes. The declaration goes first.",
    snippet: `let count = 3\n\nfn show() -> Int {\n    return count\n}\n\nprint(show())`, example: "functions" },
];
